spring:
  sql:
    init:
      mode: always
      schema-locations: ""
  application:
    name: spring-data
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: admin
    password: admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      schema: animals
      connection-init-sql: CREATE SCHEMA if not exists "animals";
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: animals
    enabled: true
